### ISSUE TITLE
How should latching alarms be supported?

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/kafka-alarm-system#4]
Alarms that are transient (ones that quickly toggle between on and off) may not be seen by operators.  Latching alarms will not clear until acknowledged, improving chances that transient alarms are seen (network outages and other odd scenarios prevent total guarantee).

There are a few pieces to this question:

1. **Should we forward acknowledgements to EPICS?**  The alarm system is generic, but the primary source is EPICS, so we need to consider if (in a separate extension) we should forward acknowledgements to EPICS (ACKS field of records with ACKT set).   I'm leaning towards "no", as Kafka will be the source of truth and we can simply ignore the EPICS latched state.  Some clients (perhaps EDM and archiver) could potentially be monitoring EPICS latched state though.  To be clear: latched state is independently tracked from active state - clients must each compute an effective alarm state themselves by querying both active state and latched state.
1. **How should acknowledgements be modeled?**   In order to avoid accidentally acknowledging a MAJOR alarm when intending to acknowledge a MINOR one (timing/concurrency issue), EPICS doesn't use a boolean for acknowledgement, but a acknowledgement per severity.  We may need to follow suit.   A separate topic "acknowledged-alarms" would be problematic because we need to tie an acknowledgement to a specific alarm instance (messages are not ordered across topics so correlation would need to be done out-of-band, perhaps with timestamps).  However, having the acknowledgement on the instance in active-alarms is problematic because currently we use a null/tombstone for no-alarm state, so it wouldn't be possible for the acknowledgement = false to exist in value payload if alarm is not actively alarming (which is exact case acknowledgement is needed).   A few options:       
   - **A.** The acknowledgement could exist in a header of active-alarms messages instead of value (payload)      
   - **B.** The value (payload) schema could be updated to no longer use null/tombstone and instead use payload that could indicate NO_ALARM (plus acknowledgement level)      
   - **C.** Move complexity to intermediary Kafka Streams app between epics2kafka and alarm system such that the alarm literally can't be cleared until acknowledged - currently the actual alarm state (EPICS SVER field, which is independent of latching) is used to determine if an alarm is "active".   A middle-man Streams app could intercept messages and conditionally forward NO_ALARM messages in particular waiting for acknowledgement first.       
   - **D.** It is possible to have different message types on the same topic.  We could have an _alarming-state_ message type and a _latching-state_ message type.   Being on the same topic (and same partition) assures message order so we know that acknowledgments apply to most recent alarming-state only.

I'm leaning towards D - two messages type on same topic.  For each type null/tombstone would mean INVALID/UNKNOWN.

The payload for _alarming-state_ messages type would contain an "alarming" enum property with possible values:
   - MAJOR
   - MINOR
   - NO_ALARM

The payload for the _latching-state_ message type would contain an "acknowledged" enum property with possible values:
   - MAJOR_ACK
   - MINOR_ACK
   - NO_ACKNOWLEDGEMENT

The producer of _alarming-state_ messages could completely ignore acknowledgement messages.  Having two different messages types on the same topic solves the issue that arises if a producer needs to produce a NO_ALARM message with a shared single message type.   With a single type the producer would need to not change the acknowledgement property, so this would be a complication in which the producer would need to query the current state of the active-alarm topic before writing the NO_ALARM message (this is why A and B are not optimal choices).  Option C is interesting, but complex, and doesn't solve the entire issue - in fact you could combine C with others as C is really about taking burden to compute effective alarming state off clients and moving it elsewhere.

**Comment by slominskir** [comment]
A related thought:  it might be nice to drop support for severity - makes acknowledgements much simpler.  The generic alarm system could simply not support severity as it is a questionable way to model unique alarms - users could instead literally define an additional alarm (in EPICS a new record).   Severity really does two things: 
   1. defines multiple alarms in a single record
   1. assigns a priority among them

As already mentioned literally defining a separate alarm is likely better than 1. and for 2. a better strategy would be to assign fixed priorities at the time alarms are registered (in the registered-alarms topic).  Unfortunately this isn't what EPICS does so we may be stuck as we have to map EPICS to our new alarm system.

**Comment by slominskir** [comment]
A related thought: clients need to be careful when they are both reading and writing to a topic as Kafka provides the total ordering on a given partition, not the client.   It is possible that concurrent messages in flight from multiple clients  and producers arrive in unpredictable order so it would be a mistake to write an acknowledgement message for example and assume it is the "next" message in the topic and immediately update the client state to say the alarm is acknowledged.    The client should only update GUI state based on the topic read callback for example.

**Comment by slominskir** [comment]
A related thought: multiple types on the same topic is tricky, especially if you're attempting to enforce schemas ([confluent blog](https://www.confluent.io/blog/multiple-event-types-in-the-same-kafka-topic/)).  When using AVRO for example there is a significant different between defining a union at the root of the value schema vs a union under the root (nested schema).  A union at the root results in AVRO Serializers being unable to automatically generate the schema for example, plus extra configuration hints are required else the Serializer will not work.   Conceptually we probably want value schema to be a union at the root so prepare to suffer a little for it.

Since we'll have compaction enabled on the active-alarms topic we must use a different key for each type of message, otherwise compaction will assume they're the same type and only keep the most recent.   Perhaps the key will change from String to AVRO structure containing alarm name plus message type.  Prepare to suffer a little for this too.

**Comment by michelejoyce** [comment]
[transient_alarm_discussion.docx](https://github.com/JeffersonLab/kafka-alarm-system/files/5430435/transient_alarm_discussion.docx)

Commenting on Ryan's previous musings.

**Comment by slominskir** [comment]
We expanded the active-alarms schema to handle our new understanding of latching.

There is no need to forward acknowledgements back to EPICS.   

Fixed in [v0.6.0](https://github.com/JeffersonLab/kafka-alarm-system/releases/tag/v0.6.0)
