### ISSUE TITLE
Shelve Group of Alarms all-at-once

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/kafka-alarm-system#7]
It would be useful to support easily shelving an entire group of alarms all-at-once.  A group may be defined as all alarms in a particular category, or in a "facility" (facility concept is also not supported right now).

The workaround is for a client to manually shelve each alarm in the group.

**Comment by michelejoyce** [comment]
Thoughts when implementing

> Injector only running 
All alarms associated with the main machine would need to be "silenced" 
That is a MASSIVE amount of alarms, which, if simply shelved, would clutter the Shelf Display. 

> Shelving policy inconsistent between alarms
Not all alarms in a subgroup CAN be shelved indefinitely (disabled)

**Comment by slominskir** [comment]
A global mask topic may satisfy the large number of alarms being shelved use-case (avoids huge list of shelved items but requires all operators to be "on the same page" as to what alarms should be "disabled" or not:  https://github.com/JeffersonLab/kafka-alarm-system/issues/10

**Comment by slominskir** [comment]
The use-case we're concerned with is disabling an entire facility (group) of alarms.  That's handled by https://github.com/JeffersonLab/kafka-alarm-system/issues/10 so closing this.
